### PR TITLE
Enforce UTF8 encoding because that is not default on Windows

### LINKED ISSUE #28: UnicodeDecodeError on Windows when building Astropy doc
Windows 7, Anaconda, Python 3.5.3, Astropy 2.0.dev19112, Sphinx 1.5.6

image

### PR DESCRIPTION
**Pull request by pllim**
Fix #28 

Works for me, but is this the proper fix?

### CODE REVIEW

**Comment by bsipocz** [comment]
I wonder why it never showed up in CI, but it looks good to me if it works for you.

**Comment by pllim** [comment]
I think this is machine dependent. Somehow the default locale on my machine is messed up.

```python
>>> import locale
>>> locale.getpreferredencoding(False)
'cp1252'
```

**Comment by astrofrog** [comment]
@pllim - actually do you know what character triggered this? I think all the CI tests here are just ASCII based which is why we wouldn't have seen the issue. But if we can figure out which character caused this, we can try and reproduce it on AppVeyor.

**Comment by pllim** [comment]
It is somewhere in the generated docs of Astropy dev. I can probably hack the Python library to give me the input value but I can't do that until I have access to the Windows laptop next week.

**Comment by pllim** [comment]
Update, the traceback did mention `0x9d`; Is that sufficient or do you need to know exactly where it is in the Astropy doc?

**Comment by pllim** [comment]
@astrofrog , would something like sphinx-gallery/sphinx-gallery#257 be cleaner and acceptable?

**Comment by astrofrog** [comment]
Superseded by #33

**Pull request closed without merging**
