### PR TITLE
Updates for tox and sphinx

### PR DESCRIPTION
**Pull request by saimn**
While trying to make a release I found a few issues with recent version of tox and sphinx ...

### CODE REVIEW

**Comment by saimn** [comment]
Sphinx 6.1 deprecates `sphinx.util.progress_message` and I'm not sure how to get rid of that one:
```
Exception occurred:
  File "/home/simon/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sphinx/deprecation.py", line 46, in __getattr__
    warnings.warn(f"The alias '{self._modname}.{name}' is deprecated, "
sphinx.deprecation.RemovedInSphinx80Warning: The alias 'sphinx.util.progress_message' is deprecated, use 'sphinx.util.display.progress_message' instead. Check CHANGES for Sphinx API modifications.
```

**Comment by pllim** [comment]
What is the future of automodapi ? Is it time we retire it in favor of something else that the wider ecosystem uses? If so, then maybe it is ok to ignore the warning.

**Comment by pllim** [comment]
Where is progress_message even called? I cannot find it here. If it is not our problem, let's ignore.

**Comment by saimn** [comment]
> What is the future of automodapi ? Is it time we retire it in favor of something else that the wider ecosystem uses? If so, then maybe it is ok to ignore the warning.

There is https://github.com/readthedocs/sphinx-autoapi but I don't know how it compares to automodapi

**Comment by saimn** [comment]
> Where is progress_message even called? I cannot find it here. If it is not our problem, let's ignore.

I don't remember exactly but it's called in some Sphinx extension I think. The problem is that in our tests we are calling sphinx-build with `-W` and there is no way that I know to tell Sphinx to ignore some specific warning:
https://github.com/astropy/sphinx-automodapi/blob/6e476f21476949d3b71dc9df19ab4feb191ac803/sphinx_automodapi/tests/test_cases.py#L134-L140

**Comment by pllim** [comment]
I ignored that warning in `setup.cfg` and now there are 3 assert errors. Do you know what is happening there?

**Comment by pllim** [comment]
Might have to put that `-W` back?

**Comment by pllim** [comment]
Now the Windows job failed...

**Comment by saimn** [comment]
The warning ignores in setup.cfg are for pytest, not sphinx.
But it works now because the warning has been fixed : https://github.com/sphinx-doc/sphinxcontrib-applehelp/pull/10 ;)

**Comment by pllim** [comment]
LoL I cannot keep up. Doesn't explain the Windows failure though.

**Comment by pllim** [comment]
@saimn , does this mean we can remove the changes to `setup.cfg`?

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
We don't do backports here, so I am just gonna "squash and merge" when CI passes. Thanks!

**Comment by pllim** [comment]
homebrew complained about the `py37-test-sphinx24` job. Something about something unavailable. I cannot care less, so I commented it out and we can move on with our lives by not buying Apple products.

**Comment by pllim** [comment]
Thanks, @saimn !

**Pull request merged**
