### PR TITLE
Always use __dict__ and ignore __slots__ on classes

### LINKED ISSUE #168: Using __slots__ hides class variables
If ``__slots__`` is declared in a class, it takes precedence over everything, including class methods and variables. However ``__slots__`` has an effect on instance attributes only, not class attributes.

The relevant lines is https://github.com/astropy/sphinx-automodapi/blob/0aad86aa90bcd7ab5b3004b732e21a3bd3d9de70/sphinx_automodapi/automodsumm.py#LL534C33-L549C33. Maybe ``names`` should also be filled with ``getattr(type(obj), '__dict__').keys()`` or something like that ?

### PR DESCRIPTION
**Pull request by Nodd**
Fix #168

### CODE REVIEW

**Comment by Nodd** [comment]
The workflow failure seems unrelated to my modification.

**Comment by pllim** [comment]
This is related though.
```
sphinx_automodapi/automodsumm.py:86:1: F401 'abc' imported but unused
1
```

I'll have to ping @eteq , @jairideout , and @pkgw based on the blame on the affected function.

**Comment by pllim** [comment]
RTD failure is indeed unrelated. I don't know why it is pulling such old versions.

**Comment by Nodd** [comment]
> This is related though.
> 
> ```
> sphinx_automodapi/automodsumm.py:86:1: F401 'abc' imported but unused
> 1
> ```
I fixed this, but there was another error : ``Reason: UndefinedError("'style' is undefined")``

> I'll have to ping @eteq , @jairideout , and @pkgw based on the blame on the affected function.

Yeah, I guess the added complexity was there for a reason ? But if `include_base` is True there is no special handling of ``__slots`` and everything works correctly in my case.

**Comment by pllim** [comment]
@Nodd , unfortunately I wasn't involved in the original design of the code, so I have no idea what it is trying to do, but hopefully one of the contributors could comment more. 🤞 

I am trying to fix RTD over at #170. If that works, I'll merge it and then you can rebase to pick up the fix. 🤞 🤞 

Thanks for your contribution and for your patience!

**Comment by Nodd** [comment]
Looks like the rebase went well!

**Review by bsipocz — COMMENTED** [review]
This could use a regression test, could you add the one you reported in #168?

Also, will need a changelog entry.

**Comment by Nodd** [comment]
OK, I'll do this as soon as I can find some time.

**Comment by kylefawcett** [comment]
I ran into this problem as well when attempting to automodapi a module containing some classes that extend pydantic's BaseModel which uses `__slots__`.  I see that @Nodd has the fix in this PR but it appears to be waiting for unit testing.  To help this along, I'd like to contribute some test I've implemented [here](https://github.com/kylefawcett/sphinx-automodapi/tree/fix/slots_plus_dict_class).

@Nodd can cherry pick the commit with the tests, or I can create a new PR. No preference on my end.

**Comment by pllim** [comment]
Thanks for your interested in this PR! Since it has been 6 months, if a new PR could be made with cherry picking the original commits here + new stuff needed to push it over the finish line, that would be great! 🙇‍♀️

**Comment by Nodd** [comment]
Sorry, I never found the time to finish this. @kylefawcett you can create a new PR, I'll be very happy if you manage to get it done :smiley:

**Comment by kylefawcett** [comment]
@pllim -- Will do. 
@Nodd -- sounds good.  I've cherry picked the commits with your fix as is so you'll still be in the commit history. I added my test cases on top of that in a new branch which will be submitted as a new PR soon.

**Comment by pllim** [comment]
Thanks, all! Superseded by #181

**Pull request closed without merging**
