### PR TITLE
Fix encoding error with automodapi_writereprocessed and py2

### PR DESCRIPTION
**Pull request by saimn**
Same as https://github.com/astropy/astropy-helpers/pull/244
Should I close the PR on astropy-helpers ? What's the next step for sphinx-automodapi, do you plan to do a release and use it directly in astropy-helpers and astropy ?

### CODE REVIEW

**Comment by astrofrog** [comment]
Thanks! I think we have to make a final decision about whether to go ahead with this standalone package, but assuming we do then we should indeed move the issues here. We should be able to release this standalone package pretty quickly.

**Comment by justincely** [comment]
@astrofrog I've started pulling this into a few STScI repos, so far with success - and would love an initial release on pypi or conda so we can pull it into RTD.  Any plans for a release or any help I can provide?

**Comment by astrofrog** [comment]
@saimn @justincely - we're going to go ahead and try releasing this as a standalone package, but let's not move issues over from astropy-helpers yet, since this is an experiment for now. If you find issues with it, you can open issues here, but no point moving issues over from astropy-helpers until we are sure we are removing the code there.

**Comment by saimn** [comment]
@astrofrog - Ok, great !

**Comment by justincely** [comment]
@astrofrog sounds great!

**Comment by astrofrog** [comment]
@justincely - I've made an initial release on PyPI - let me know if you run into any issues!

**Pull request merged**
